function plotScaleBars(P, Color, cAH, X0, Y, VertLine)
  plot(cAH,[X0,X0+P.PMM],[Y, Y], Color,'LineWidth',1, 'HandleVisibility', 'off');
    text(cAH,X0-P.ScaleBarSep,Y-5,'L','Rotation',90,'horiz','center',...
      'FontSize',P.ScaleBarSize, 'Color', Color)
    text(cAH,X0-P.ScaleBarSep,Y-30,'M','Rotation',90,'horiz','center',...
      'FontSize',P.ScaleBarSize, 'Color', Color)

  plot(cAH,[X0,X0],[Y,Y-P.PMM],Color,'LineWidth',VertLine, 'HandleVisibility', 'off')
    text(cAH,X0+5,Y+P.ScaleBarSep,'A','horiz','center',...
      'FontSize',P.ScaleBarSize, 'Color', Color)
    text(cAH,X0+30,Y+P.ScaleBarSep,'P','horiz','center',...
      'FontSize',P.ScaleBarSize, 'Color', Color)
    text(cAH,X0+16,Y-P.ScaleBarSep,'1mm','horiz','center',...
      'FontSize',P.ScaleBarSize, 'Color', Color)